#import "/template.typ": *

== Dzogchen meditation on the nurturing, majestic mind

Let's do another 10 minutes of non-meditation. Okay? So we're really interested in this place of our mind... at first we're interested in recognizing, well where are the thoughts coming from? Where are they abiding? And returning? And all the sounds right now, notice the mind that's holding all the sounds. There's a awareness there. It's very, very close to you.

And it's not just awareness---it's this nurturing, beautiful, majestic mind imbued with compassion and honesty, purity. So there's a purity there with you as you're hearing things right now. Pure mind. And everything in your visual field is also in that mind. That's why we leave the eyes open; we don't mind the sounds and the sights.

So you can notice the same majestic mind of yours within the hearing, within the seeing, within the thinking and feeling. So this way we come home, we're no longer lost in the movements of experience. We can still have thoughts from that vantage point. So it becomes very easy, everybody, just noticing something that's always been here like space unmoving like a mountain---we just leave awareness alone. Let it embrace the mountains, the sky, the earth, the air, the fires, all the oscillations and fluctuations of experience. Nothing changes awareness.

So like I said last session, if I come here today in a really bad mood because I ran out of bananas or something like that, something serious like that, then maybe my body is crunched up, my brow is tight, and my frontal lobe is thinking, "Oh, where am I going to get more bananas? I am lost without this potassium and I'm creating narratives, and I don't know how I'm going to get more bananas, where I'm going to get them from? The store has run out and it's devastating." This is my narrative now, right?

So I come here in the 10 minute session and some dog yogi asks me to just let it be. Just don't do anything about my anger about bananas. And so I sit here and I say, fine. You see my body tightening up like this, right? Shoulders, neck, holding the devastation of no bananas. So then, okay, I'm just gonna let this be. And now body is starting to soften, right? Clear. Things are coming out of my neck, out of my shoulders. I'm still thinking about bananas a little bit, but I'm letting it be. Ah this is nice. This feels less contracted. My brain feels better. "Yeah, but I gotta have the bananas dammit." See? And I crunch back up. All right, just let it be, let it be. Let everything... settle in its own place.

And so now somatically my body is returning to equilibrium, naturalness. The mind is clear of all bananas. I can actually abide here with not a single thought and a great clear openness. And the undertow is also able to breathe now because I'm not crowding out my traumas, my past karmas. I'm not drowning them out with worrying about bananas. So it's only because of awareness that you don't go bananas, okay? Because otherwise you would be stuck in these thoughts.

And I use a very light example because it could be your parents, it could be your ex-partners or your current partners, it could be your job. Um... What is occupying your mind? What is grabbing your attention? You can release that back into awareness. And then let your anger, your depression, even your elation, let it be. Let it breathe in awareness. And then the practice becomes about, even if I get up right now and I go to work on the house or something like that, awareness is still there. I'm just letting it be. And all four of these postures, okay?---just sitting, standing, walking, and lying down.

So I know it seems a little repetitious, but once you see, once you become aware of awareness and you just get used to letting things settle in their own place---well you are free. There's a great boundless freedom that becomes accessible. And I've seen it over and over and over again with this group. And throughout the lifespan of Dzogchen, the traceable lifespan, the visible lifespan anyway, countless people have experienced utter freedom from this simple recognition. And they base many, many hundreds of years of scriptures on this very simple recognition.

So any questions about recognizing the nature of mind? Awareness, mindfulness, all these names they have. Recognizing that and familiarizing, or any questions about self-liberation? How that happens, how we can be free by not doing anything. You all got it by now, right?

#archive_minimal("November 25, 2025", "Dzogchen meditation on...", "https://www.youtube.com/watch?v=-7cr5CWSO_w")
