#import "/template.typ": *

= Mind as vast space: Dzogchen's all-inclusive meditation on the whole environment

Recorded October 18, 2025 (9pm ET session).

https://youtu.be/EM73j-bs504?si=BrhyKgWrhHverZIg

You know, even in modern science, they're starting to treat the results of meditation as beneficial because we're starting to have a holistic, living consciousness.  For example the hemispheres of the brain are beginning to synchronize and work and be active throughout all the lobes of the brain.  So this is why neuroplasticity and meditation have had these amazing successes and advances, right? Then they took it even further with the holistic consciousness, the whole body, left and right, up and down, starting to have a kind of microcosmic synchronicity, a harmony, because of meditation, right?  And that's linked to the nervous system and the brain as well, and everything.

But then, what about the outside?  You see, we can treat the outside like a living organism.  Every storm that happens, every person that we run into, is like a feeling in our arm or something.  Or the storm is like a stomach ache maybe, or what we would call a stomach ache.  A sunny day is like the body feeling light and healed up.  And so I don't want to define that for you, but to begin to look at this entire phenomenal reality as a living being as well, as a system that can harmonize within awareness, and you see?  

So there's the body harmonizing, which is amazing, we have all these benefits from that, we have the brain and the body and all that, but then all the energies, too, right, are beginning to synchronize and harmonize and self-liberate congestion, from the effortless abiding.  And then, what about the external, that's not really included in many approaches anymore?  To say, "Come on in to my awareness practice, World,", right, all these happenings, all these sensations, feeling, smelling, tasting, hearing and seeing.  And when that starts to be visible, just like our tension in our shoulders; "oh, there's tension on the environment", just like that.

And then mind, they say over and over again, is like space.  That's the fourth samaya, also, oneness, and the second samaya is spaciousness right?  So for that to be possible, we cannot be contracted into something.  Then, there would be no spaciousness.  So that gives us a clue that we're not really in the second samaya of openness, spaciousness, if we're contracted into something.  So there's a different ...there's an opportunity here.  Something else to try, aside from perhaps worrying, or being in a kind of fear, or maybe even some temporary happiness or something like that, instead of being isolated, compartmentalized into that.  

Because you, as an awareness practitioner, you know, "This is not spaciousness.  I'm contracted into something right now."  And then as awareness holder, you also have the choice:  "Wow, I can release this."  If you're very stubborn like me, it may take a day, to finally forgive somebody, forgive yourself, forgive the environment, what's happening in the environment.  

So is that making sense, beginning to pretty much radically include our environment, as a co-emergence of mind, as another system of mind, just like if there's a dream?  A dream scientist pays attention to every object that was noticed, that manifested in that dream, because every object has a deep, ineffable significance behind it.  If you're getting chased through a city, there could be apartments that you're running by.  One could be a horse stall; another could be a computer lab.  These all have a kind of psychological significance.  It's a psychological iconography. 

So the environment is very significant; it's always being held within the mind as you're having the dream---every emotion, every thought, every sensation.  And then the construction of the environment---totally random.  So we have to understand, that when we talk about your higher mind, or the lucid mind, metacognition, outside of thoughts and emotions, it's not necessarily pretty.  Thus we have samsara.  Thus we have stress and suffering.  So we sometimes say, "Oh, once I get out of my thoughts, it's gonna be---I'm accessing my higher mind."  But that's messed up, too---not just your thoughts! That's tangled up and congested as well.  So, the lucid mind itself needs to untangle and self-harmonize.  

And so to do that, your lucid mind...Imagine, just entertain the possibility---I'm not asking you to believe anything---as you venture  into the depths of your mind, is it possible that right now, my mind's holding up an entire environment?  That every object is a co-emergence that corresponds to what I'm thinking on the coarse and subtle levels?  Then you can almost feel the very thought that's holding and reifying the elements.  Unless you're on acid---then they might go away!  But I don't think anybody's tripping right now on acid.  We're just tripping on samsara.  We're on the great drug of ignorance.  The hardest drug, that causes the most convincing delusions.  

So like that, we include the entire environment.  Is it possible?  You know, when you take a walk, or even right now---you notice that your mind is subtly there, outside the body. And you can breathe into that.  (Dawai takes a deep breath and then pauses.). Just because you were isolated into the body, and behind the eyes even, into thoughts, doesn't mean you have to be now.  (Dawai pauses again to let the sangha experience this.)

And then mind is cosmic, right?  Vast beyond the earth, beyond the moon, bigger than the sun.  And so, through introduction to awareness, clear light awareness, this is naturally present, purely present---we don't have to turn it on.  It's present as vast space, mysterious, and completely beyond anything we could conceptualize. 

Somebody posted a dharma meme that had a sign.  Somebody made a sign outside of a fence.  It said "ENLIGHTENMENT IS ...something" .  And they tore out the part where it said "something" , you know, so it just said "ENLIGHTENMENT IS..."  and there was a big ol' hole in where it used to say something.  

Yeah, so, we can leave it mysterious, right, but that's what they talk about sometimes---it's been translated as "the void"and things like that.  It's because it's so open and infinite.  And all-encompassing.  Your mind.  #btw[Dawai pauses]

Awareness practitioners in the phase of self-liberation, entering the stream of nirvana, will begin to feel so familiar with this, and so comfortable, that it's like your favorite parent, out of all your lifetimes, is holding you.  And nothing could ever mess with that!  And instead of trusting this little conventional reality, you start to---just like everything else, you have to warm up to any kind of hobby, any kind of trade; you start to warm up to this mind.  Of course it's new, of course it's a little foreign to us, and yeah, we're gonna be more cozy in our conceptual reality at first, until we can walk on our own two feet, until we can ride the bike with no tricycles ....or "no training wheels", 'scuse me.  I haven't ridden either of those in a while, 'scuse me.

So, any comments or questions so far on that, essentially the fourth foundation of mindfulness, the togyal aspect being introduced?  Without the light aspect, it may take longer for things to decrystallize and become less convincing.  See, the yogis like Longchenpa, they're just asking us to entertain the possibility that this is like a dream---mind is omnipresent.  And just that little bit of pliancy, of entertaining the possibility, will start to reveal some evidence and proofs for us.  

And don't go in blindly, you know.  We definitely step in diligently, and we verify as we go, no problem.  We even have concepts to throw around.

Well, it's getting a little chilly out there, so let me let the Luna-girl in, and then, Sangha 1, we will get to you.  (Dawai goes to the door and talks to Luna, the dog) Come on, Luna-girl.  (Dawai comes back to the sangha on camera). Still warm in the insulated house, though.  Ahh, hard work pays off.  In the Doggy House, the Doggy Shed.

Ok, my friend, hi Sangha 1, or is it Sangha 2?  I can't see anybody right now. 

SANGHA 1:  Yeah, just me...You talked about being held by like your, the best parent you've had in lifetimes.  Yeah, that same kind of love, could you cultivate that, or is it more of like letting go into awareness as it appears as such?

DAWAI:  Well, you already know the answer, but you know, this...cultivating  is provisional, and according to the previous yanas, before Dzogchen.  But Dzogchen sees that sort of as splashing around in the water, right?  It seems like you're cultivating it, but it's all already compassion, so, you don't need to...You can't really cultivate, and Dzogchen specifically is antithetical to cultivation.  They definitely have those terms, and utilize those methods, and they can help people, perhaps, be kinder, and tune in to their natural compassion, but we want to be relentless---at least if you're following it according to my opinion---we want to be relentless with... that we already have our compassion there.  We know it, it's familiar to us.  And so, when our contractions fall away, that's what's left over:  our natural kindness.  And it could take awhile to become less disgruntled, or less aggravated about situations that we have on our mind, right?  That could take awhile. Parental situations tend to bug us, cultural situations really can ignite us into echoes, feelings, that we hold onto, thoughts we hold onto, clouding our natural compassion, that absolute bodhicitta, right?  So here, definitely,  Dzogchen is synonymous with absolute bodhicitta, rather than this aspirational which they would have in the Mahayana. And then the Shravakayana, they don't care about nobody but themselves...No, I'm just kidding, they also have the loving kindness practice.  

Okay.  
I've gotta say, you know, in my personal seeming appearance of experience, and things like that:  starting to have some kindness come out again, after I was pretty angry and everything; that's, to me, the true miracle, right?  There's a lot of other stuff that comes with this, that I didn't expect, but, just finding some peace, and confidence in the ineffable, confidence without cause, peace without cause, without any intoxications, without bodily comforts, even...

You know, that's why we're very lucky to have people like Rolpa presenting so openly their experiences, like, presenting their challenges, and still finding this great peace.  To me, that's truly miraculous.  Why this is working for people, right?  We just  present it for them, in the most skillful way we can, and they get some freedom.  

And you-all can do that for each other, right?  Once we get to a point where we're confident enough, or maybe we're just excited, we're talking about it, we can really have that butterfly effect.  As long as we're dealing with authentic practice, we're being honest with ourselves and others, we're not just psychoanalyzing, projecting onto others and things like that---it's like lending a hand when somebody slipped and fell, or something like that.  It's gotta be authentic from the heart, spontaneous, unplanned, uncontrived.  We don't want to "help" people (in air quotes), overly help people right?  We don't want to proselytize; that wouldn't be according to Dzogchen tradition, anyway.  And so like that, it can have a tremendous effect on the collective, to just have this awareness practice. 
