#import "/template.typ": *

== Dharma talk on familiarizing with the view

As usual, I'm very happy to be here in this gathering amongst these beautiful people who are brave enough to look into their own mind and turn the lights on in their own life to ensure freedom for themselves, but also for those around them and the collective. When you add awareness into your life, it changes everything because now you can see what you're doing, you can see what you're saying, you can see what you're thinking, and you're not on autopilot with a kind of involuntary programming. You begin to break the programming and the momentum of pre-programmed habitual tendencies.

So it's very, very powerful just to add a little bit of awareness into your life, and it's just as simple as self awareness. But typically people think we have to _do_ the self awareness. But in paths like Dzogchen and I don't know, maybe some Mahamudra and things, here you get _pointed to_ awareness. And of course, we want to really familiarize with that, and first it'll be vague and the power of awareness is also obscured. What is it obscured by? Anybody want to take a guess? The pre-programmed conditioning. If I have a clear sky here, but I have a pre-programmed habit of putting three clouds in every time, every 30 seconds, three clouds roll by.

Our habits are like that, when you start to see the thoughts that disturb you, they're repetitive, and that's how we know they're conditioned. When you start to see emotions and states of consciousness that perhaps appear as discomfort, disharmony that in Sanskrit _tukka_, you see that with an awareness, and so all these things begin to really be able to breathe... and within presence, the karma doesn't get any more programming. So that same old friend, that same mood, that sadness, that loneliness, that worry, you've had it many times before, and so that's how you know it's programmed.

And so lots of conditioning tends to overwhelm us because it's compounded. Next thing you know, we're under the sway of layers and layers of pre-programmed conditioning, kind of piles up. And so in the practice of letting be, which is the highest yet simplest meditation practice in the Dharma, you're letting be because you're letting the karma unravel itself. And we can tune into this somatically, and that should give us our proof, our verification, oh yes, if I leave this alone there's self-harmonization.

So I was saying earlier, when we're really stuck in our thoughts, the nervous system in the center of the brain, it'll clench up like this, #btw[Dawai clenches his fist], and you can feel it along your back, your neck and your shoulders will be tense, and then all the way down your spine, and most likely in your lower back,nd even pulling on the nerves in your legs, your stomach. So what happens when you allow a little bit of time for that brain, that thinking, thinking, thinking to relax? Well, then the whole system has to follow that. And you'll notice your stomach tension is coming out of there, tension is coming out of your lower back, out of your shoulders, your neck.

And so not just this whole session is a Dzogchen session, but like [sangha member] was saying, all day becomes a kind of self-liberation, illuminated experience. And luminosity itself is revealed for those who really want to take it there. Yes, this practice can ensure quite a bit of freedom in your life. Freedom from worry and panic and all kinds of things. But also the obscuration of luminosity, the obscured luminosity, that which is obscured is revealed. And we find that which is there before the words. That which is there before the thoughts. Before the emotions, before the feelings, there is something. #btw[Little Bear the dog says "woo woo" in the background]. Before the bark... woo woo... Little bear, before the woo woo? Nothing comes before the woo woo.

So this is very powerful, all of our experiences now have a basis, so you're not caught up and trapped in the experience. And we say this many times, you know there's so much I could say about this. When it's conditioned, you have the eyeballs seeing sense objects. You have the ear consciousness hearing sound objects. The smell, the tactile sensations, the taste. You have all these things happening, the five senses plus conditioned thoughts and emotions making the sixth. And then the seventh aspect of your mind, conditioned mind, is the egoic construct, the conditioned self.

And that all has a basis. If I say, "I love the bird," well, where's that I? That's in the eighth consciousness, sometimes called Alayavijñana. Sometimes termed Kuntuzangpo or Samantabhadra, The All Good, when we're talking about the counterpart to conditioning.

So basically you have the lake, and when you stir it there's a sense of separability---that's the seventh egoic consciousness. The "me" isolation that's making a duality. And then within that whirlpool, you're getting caught up in the reflections within the whirlpool. So you're seeing stuff but they're only your own reflections. So you have this entire eight aspects of consciousness, but when this starts to sort of untangle, then you have the five wisdoms, which are together, like the five lights or the four lights within clear light.

So think of a rainbow. Now all those colors are sort of intertwined and overlapping, and the idea is right now, everything, the elements, your body, empty space itself, is the five lights being reified and crystallized into empty appearances.

Any questions about that part?

Once you get that a little bit... the idea in your awareness, then you can see, well is this true or not? Is there luminosity? Of course we do the Tögal practices, many of you have had experiences when you were children with light phenomenon and the dream world, all kinds of things can compliment and lend itself to the truth of luminosity. Making sense, right? Okay.

So I think that's pretty much all I wanted to introduce and share a little bit about what's happening with self-liberation. Well, they call it Ayatanas or the eight aspects of consciousness are liberating into the five wisdoms.

And of course you have this pride liberating out into the wisdom of equality. And the earth element liberating out into the yellow light. And then you have this jealousy liberating into all-accomplishing wisdom. The air turning sort of to the green light or associated with the green light. And you have desire sort of transforming into the wisdom of discernment and that's the red, a color red being exposed from fire or heat. Then you have anger being revealed as mirror-like wisdom, and so that's typically associated with water being liberated into blue, the color blue. And then Ignorance itself is liberated into wisdom of dharmata, so all phenomenon, emptiness essentially. And space itself is liberated into clear light awareness. So that's the basis for the other four colors there.

And remember, if you want to remember the elements, you can use that little acronym SAFWE, but add a W between F and E. So space, air, fire, water, earth. And so that's how conditioned consciousness... so you'll have things like the sixth consciousness being associated with like pride, I think it is, and anger. And so the eighth consciousness is associated with the wisdom of dharmata. And so you have all eight of these that correspond with the kleshas, which are the five poisons of anger, jealousy, and all these things. But they also correspond with the five senses, including the... bark bark... 

#btw[Little Bear arrives for a hug]. "Hey buddy. How's it going? Oh... oh, I see."

So yeah, you have this typical eight consciousness aspect which is associated with conditioning, and the elements also associated with conditioning. And then if you have another side of the coin, have the five colors and the five wisdoms. And so remember the five colors are the five wisdoms in Dzogchen. So the colors are alive, they're kind of like mind colors that this whole reality is made out of. It's very powerful stuff, it's a rainbow painting.

What was that book by? Namkhai Norbu or was it Tulku Urgyen? Rainbow Painting? Yeah.

And when you get introduced to the Tögal aspect, I do think it expedites that luminous quality. Okay? And I can't emphasize this enough. All the stories, lots of sharing, are really fascinating and interesting and can be useful; but all we really do here is you're introduced to this meta-awareness, meta-cognition, and you either believe that or you don't. You either have a solid recognition of that, or trust, or a faith even. I don't know... But when you do, you see that spaciousness; and that becomes your refuge, that becomes your guru. It's all fine and dandy from there.

So you get pointed out to this. A lot of people won't recognize it, or you know, they're just not in that position yet for recognition of the nature of mind for one reason or the other, it's totally fine. But then that's all we really... you know, all it takes for your liberation. There are no other stories, nothing else you have to do, no other evidence, anything. Just see this and warm up to it. Yeah.

And a lot of people want to wrestle around in their head with the view or role play as a yogi and things like that, which I think is fine, there's nothing wrong with the role playing and the religious stuff, but it's really about seeing awareness and familiarizing. There are no elaborate concepts, no deep philosophy, anything. Nothing else required from you. Making sense, right? Okay. Not even your email.


#archive_minimal("March 20, 2026", "Dharma talk on fam...", "https://www.youtube.com/watch?v=lgl1rwSqG-o&t=18s")
