#import "/template.typ": *

= Dharma Talk on Dzogchen Responsibilities

This one is basically is about some of our... (somebody's unmuted there) So, traditionally they would call them dangers, but please don’t label the video that and I don’t call them dangers. Things have shifted a little bit as we went along here. So what used to be a traditional trope like, "Well, you need preliminaries before you get to Dzogchen." This is to avoid dangers. I would say they’re more in our group responsibilities. One of the biggest things I think the teachers talk about and teachings talk about is our responsibility towards karma.

Until you’ve fully actualized or until emptiness has been fully actualized, then of course skillful means and wisdom, compassion, empathy---of course, stay with those. We don’t need to abandon compassion or skillful means, those are synonymous. We don’t need to abandon... because we think everything is empty or everything is dreamlike. This is a kind of hedonistic nihilism that I imagine has been promoted or actuated throughout history, and still today I have seen it. I’ve seen a microcosm of it even when these teachers are telling you, you know, "Everything is perfect," "Everything is pure consciousness."

And so in that conversation, I’ve heard somebody say, "Well what about my sickness? I’m feeling really terrible today." "It’s all perfect," and they’re laughing and da-da-da-da. Well this is the kind of irresponsibility that I’m talking about. If someone says, "Oh, I’m sick," you don’t just infer the idea that everything’s perfect. No, your empathy’s there. "Oh, I hope you get better." "You’re already better." No, it’s not. Come on, guys. This is not verbal gymnastics. This is not mental gymnastics. Dzogchen is different. It’s fine to care about your friend if they’re sick. It doesn’t mean you’re somehow negating primordial purity. So, I don’t know if I need to expand on that too much, but any questions about how we don’t need to negate this skillful means?

I think most of you here are going to be all right because we always emphasize benefiting all beings and having this dedication and all kinds of things. We don’t just depart from what is known as karma. So until you’re really free of the dream, you got to kind of play by the dream rules. Okay? The main point there.

And then another so-called danger, danger-danger, that gets mentioned, which I mean, I think it’s better that you have dharma dangers than crack cocaine dangers and things like that, you know? I’m like, "Well, at least the people are in the dharma, it can’t be that dangerous." So anyway, danger is a dangerous word.

(Dawai reads a chat message). "So what about all those sharp weapons?" 

Dawai: I don’t know if that’s a reference to a their teacher or if something else is happening there, but if you do have an actual question, make sure I don’t miss it, okay? 

All right so, another possible obstacle along your way, again, not in these gatherings if you stick with it because you’re going to have a guide. You’re going to have lots of guides because of all these profound sharings which are typically in the context of self liberation or familiarization. But another one is you know, right along what (EDITOR: Originally says Mapang was setting) someone was setting as a theme, or maybe the theme was preset. But this is the idea you know, that we’re going to feel awareness or that we’re going to feel enlightened. No, anything that feels enlightened is not self. Remember the five aggregates that Buddha Shakyamuni taught: that form is not self. The feelings, the thoughts, the body is not self. Conditioned consciousness is not self. So we’re not concerned about "am I enlightened." We’re concerned with what’s here right now that’s unenlightened? And when that unenlightenment is gone - no concerns.

So there’s never a conditioned consciousness to apprehend purity, enlightenment. There’ll never be a part of you that says, "I’m enlightened," because that would be conditioned consciousness. The only thing you can ever know in terms of enlightenment is what’s not enlightenment.

(Dawai reads a chat message). "What’s not enlightenment?" 

Dawai: You tell me, you love these questions Sanga 1. What's not enlightenment? 

Sangha 1: Ignorance. Confusion. 

Dawai: Yeah, we can speak conventionally here because if you had the urge just now to say "everything’s enlightenment", well then your mind is going into an extreme. Conventionally speaking, people are still dreaming even though it’s all enlightenment. So yes, when you don’t see the purity, when your mind for some reason turns away from perfection and begins to manifest imperfection or the illusion, the appearance of imperfection, then that’s here. 

Just like when you go to sleep at night, if you don’t have any dream, let’s say you can be a blank canvas, then it’s just pure cognition, empty of any referentiality. Then you start to make a character. "I’m in this dream." Well, that’s a separation. That’s not self. That little character that’s walking around the forest, that’s not self. That’s not you. 

If you feel a pain, that pain that you’re feeling there is unenlightenment, because nothing ever got unenlightened, nothing ever got impure. But you thought, when you allocated your consciousness into subjectivity, you thought through that separability, you think there’s unenlightenment. 

And so what’s here for us right now in the presence? Is a contraction, is a story, is a something keeping us out of enlightenment. And so again, when everything is cleared out of your presence, any kind of contracting into smaller dimensions is cleared. Then oh, I’m here. Who’s enlightened? Where is enlightenment? It’s all enlightenment.

But if I start thinking, "Oh, today is a crappy day," that’s not enlightenment. Ultimately yes of course it’s pure energy, empty cognizance, but I’m tricking myself into unenlightenment. And then I create this character that says, "I’m unenlightened and I need to get enlightened." And then I go searching for lifetimes, many many years, for enlightenment, but without that character who’s labeled unenlightened I wouldn’t be searching for enlightenment.

Or the character just gets highly involved with the sense world. We dress ourselves up, we make ourselves up; all this stuff to become more enticing to the senses. Every sport you can name is all trying to chase a sense object. They’re obsessing, they’re training how to be better at chasing the sense object, how to kick the sense object through the poles, or how to carry that sense object the best, or how to shoot that sense object like a basketball through the net. And it’s just this little ball that everybody’s focusing on. This is samsara. We’re all focused on a ball. We’re all kind of chasing the ball. And then they make fun of the dogs for being too simple, you know, because they chase the ball. You’re also chasing the ball.

So more of these so-called dangers if you don’t have guidance, if you’re going into it isolated, or if you have some Rinpoche who gave you instructions and then you don’t see him for years and years and years, and you only meet him one time maybe, well then you’re on your own with the Dzogchen practice. I don’t believe in that. I don’t believe in leaving people alone. I’m a stalker. I will email you to see if you’re all right. I know it’s crazy, I’m totally out of hand. I’m so happy that I met other people in these gatherings who actually care about people in a group. We don’t expect everybody to care about each other, but they know each other’s names. They come here, they enjoy each other’s company. Wonderful.

So, the other pitfall is that if you don’t have guidance, you could fool yourself into thinking, "Oh, this is awareness," when that’s really just a nyam, just a conditioned experience. And then it goes away and you say, "Oh, I got to get that back. I wasn’t in awareness. The first part of my day today, I was not in awareness." See how that doesn’t really make sense. So the experience that you have, if you’re feeling calm and passive, if you’re feeling bright and spacious, it doesn't matter. If we try to reify some state and duplicate it and repeat it, this is more conditioning.

The mind is so finicky that it’s like playing one of those little games; when you lose, your entire emotions feel down. Oh, you win, you feel high again. Sports is like that. Video games is like that. Ecstasy is like that, the drug. Yeah, people get on it and their... (Dawai reads a chat message). "Work is like that." Yeah. ...They get on these drugs and their emotions go up and down so quick depending on any little thing, any little thing.

This was fascinating for me when I was playing chess against the bot. And if I would lose, I would actually feel a little sad or some kind of little feeling, right? And you don’t have to be like that. You don’t have to constantly get pulled up and down, up and down, up and down, unless you want to. "Oh, this made me sad. Oh, this made me happy." "Oh, this made me sad. Oh, this made me happy." Wow, what a way to be.

So the conditioned consciousness, that experience, that one of the five aggregates there, is not what we’re after. Now we have somatic indicators: "Oh, this has come out of my conditioned consciousness. I noticed it while it was coming out and it’s gone." But the second you say "this must be enlightenment," nah, that’s another conditioned consciousness coming in. So you can notice yourself becoming untied. Sure. You can notice yourself: "Oh, I’m not going up and down, up and down, with every little thing that happens." It’s almost like your focus turns in on itself and it says, you know, "This feeling right now is okay. This is enlightenment." The stomach ache, the pain, the sickness, this raw energy without inference exposes itself as primordial purity.

So it’s freedom from the five aggregates, freedom from the conditioned experiences, that is liberation. I have seen this; some gurus, some teachers, they try to maintain a state of enlightenment. Many well known teachers like Culadasa does that in _Mind Illuminated_,  recommending to maintain a liberated state. And obviously that’s problematic, okay? 

So, aside from that, these various states confusing you and tricking you thinking, "Oh, I’m enlightened now or I am liberated now." The most we can say is, "I’m awake now", when you’ve seen awareness. And even that is a kind of false statement, but you can get away with it. We don’t want to just stop our conventions, that’s what makes Dzogchen so great. It brings enlightenment and conventional truth into a union. We can talk about it openly with the subtle paradoxes or contradictions and whatever might be in there that we have linguistic problems with, like "oh this is dualistic speech", it is no problem. We can speak in healthy paradox. 

Okay. So, any questions or comments on this topic going on? Yes. Hi.

Sangha 2: Yeah, what you just said is something that’s been really striking me. When I look at texts and it talks about cutting through the root of samsara and nirvana. You know, it’s not saying okay we’re going to get rid of samsara and make sure we always have nirvana. It’s saying no, we’re going to go through both. And every time I see that there’s kind of like a "whoa, this is going deeper than I thought." But thank you, yeah, I feel like I’m receiving the transmission today and it’s really wonderful. Thank you.

Dawai: Yeah, and so it’s interesting because as you’re experiencing self liberation, which could be termed nirvana, you realize that there's an inversion there. You realize that what is liberating is pure. In this approach that’s explicitly outlined, it’s not mysterious. That’s why our group is actually a very, very powerful group. We’ve given rise to this teaching _Beyond Recognition._ There are no real teachings going beyond recognition that are synthesized anyway. Yes, there's Lamas and Rinpoches, I hear them complimenting our style: "they’ve never seen it before." That’s because no one person invented it; it came from a group of yogis.

Yeah, it’s a beautiful, beautiful opportunity we have here, and truly a treasure that’s been revealed to us. Just that little nuance there that, "oh, I’m self-liberating. Everything’s coming off of me," and then all of a sudden, "well, I don’t want this to come off of me. This is great. My own anger, my own sadness, everything, it’s wonderful." So, self liberation has a complete mystical side to it. Just like life, they say 95% of our reality is unknown dark energy. Well we can make space for that as yogis, you know, that what I’m witnessing is about 5%. What I’m involved with, what I’m addicted to is about 5%. What else is going on here? Just asking that question alone is quite empowering.

Okay. So, any other questions, comments about this stuff? Look at all this pristine water. Excuse me while I enter the gates of heaven. (Dawai drinks water and pretends to choke) I’m just kidding. 

All right, well, that concludes I think that talk on just a couple preventative traditional dangers considered as part of the view that were quite adequately set up to safeguard against like that. You’re not going to last very long in here if you’re contriving the awareness practice. Your sharings will reveal that, to yourself most of all, and you will see, "Oh, this is probably just some kind of nyam, some kind of conditioned experience." And that’s the only way great freedom can take place - that great spaciousness. If we confine ourselves into some state of consciousness and say, "Oh, this is enlightenment," uh uh, you’d be missing the entire spaciousness aspect.

#archive_minimal("April 24, 2026", "Dzogchen Responsibilities", "https://www.youtube.com/watch?v=mXCECmDc1jY")
